apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore  # 组件名称，代码中需引用此名称
spec:
  type: state.redis
  version: v1
  metadata:  
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "true"