apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: orderstore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:7379
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: false
  - name: keyPrefix
    value: orderstore