apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rpaclient  # 组件名称，代码中需引用此名称
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:8379
  - name: redisPassword
    value: ""
  - name: enableTLS
    value: false
  - name: keyPrefix
    value: rpastore